credentials:
  usernames:
    souvik:
      name: Souvik
      password: $2b$12$HuSW2a6llHoCaRd6kH5ehOok1XV1lClUR2uc8vJb5npr/dVYY9RPG  # Hashed version of "123"
      logged_in: False
    sayani:
      name: Sayani
      password: $2b$12$HuSW2a6llHoCaRd6kH5ehOok1XV1lClUR2uc8vJb5npr/dVYY9RPG  # Hashed version of "123"
      logged_in: False
cookie:
  name: cookie
  key: key  # Random string for cookie signing
  expiry_days: 0